SELECT EMP2.EMPLOYEE_ID, EMP2.NAME, COUNT(EMP1.REPORTS_TO) AS REPORTS_COUNT, 
       ROUND(AVG(EMP1.AGE)) AS AVERAGE_AGE 
FROM EMPLOYEES AS EMP1
JOIN EMPLOYEES EMP2 ON EMP1.REPORTS_TO = EMP2.EMPLOYEE_ID
GROUP BY EMPLOYEE_ID
ORDER BY EMPLOYEE_ID;